name: On Website Deploy
"on":
  push:
    # (1)
    branches:
      - "main"
defaults:
 run:
  working-directory: ./explain_rol
jobs:
  build_and_deploy_web:
    name: Build & Deploy Flutter to Web
    runs-on: ubuntu-latest
    # (2)
    steps:
      - name: Create .env file 🔐
        uses: ozaytsev86/create-env-file@v1
        with:
          INPUT_ENV_API_AUTHORITY: ${{ secrets.API_AUTHORITY }}
          INPUT_ENV_API_PATH: ${{ secrets.API_PATH }}
          INPUT_ENV_API_KEY: ${{ secrets.API_KEY }}

      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          
      - name: 🌍 Enable Web
        # working-directory: "explain_rol"
        run: flutter config --enable-web

      - name: 📦 Get packages
        # working-directory: "explain_rol"
        run: flutter pub get

      - name: 🏭 Build Web Application
        # working-directory: "explain_rol"
        run: flutter build web --release

      # (3)
      - name: Make copy of artifacts
        run: |
          chmod u+x "${GITHUB_WORKSPACE}/createandcopytofolder.sh"
          bash "${GITHUB_WORKSPACE}/createandcopytofolder.sh"
      # (4)
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit the artifacts.
